### ISSUE TITLE
There's no visual distinction between new pages and pages that I've already read

### ISSUE THREAD

**Issue by rsfinlayson** [nt1m/livemarks#102] opened 2018-12-15 00:09 UTC
There needs to be a visual distinction - in a feed's folder in the Bookmarks menu - between new pages, and pages that I've already read.  Otherwise it's too hard to tell which pages are new.  (The old "Live Bookmarks" feature in Firefox had this.)

**Comment by nt1m** [comment] 2018-12-15 00:12
Duplicate of #17

**Closed by nt1m** 2018-12-15 00:12 UTC
