### ISSUE TITLE
Not possible to read Youtube RSS Feed

### ISSUE THREAD

**Issue by DonDante** [nt1m/livemarks#55] opened 2018-10-29 06:18 UTC
Add-on working great so far. However, I am running into trouble importing my Youtube channel XML feeds. This used to work with live bookmarks from Mozilla using the URL: 'https://www.youtube.com/feeds/videos.xml?channel_id=CHANNELID" . It looks to me like the Youtube XML fomat is not readable in Livemarks. Would be amazing if you could fix this.

**Comment by evilpie** [comment] 2018-10-29 11:03
Do you see any output in the browser console (Ctrl+Shift+J) when opening the feed preview page? Especially something like tracking protection blocking the request? Does it work in Safe mode (or without extensions?)

**Comment by DonDante** [comment] 2018-10-29 11:16
Hi,

I disabled content blocking for specifically that page and Livemarks was able to display the page.
Thank you for the clarification.

**Comment by evilpie** [comment] 2018-10-29 11:20
Thanks! Duplicate of #38

**Closed by evilpie** 2018-10-29 11:20 UTC

**Comment by MickGe** [comment] 2025-04-21 19:25
I had the same problem. It comes from Decentraleyes add-on.  
I had an exception, it works!

Thanks!
