### ISSUE TITLE
Daily MtG feed does not display list of articles

### ISSUE THREAD

**Issue by Mikaill** [nt1m/livemarks#209] opened 2019-10-27 17:39 UTC
**Feed URL:**
https://magic.wizards.com/en/rss/rss.xml?tags=Daily%20MTG&lang=en

**Repro:**
Create an RSS folder for the specified URL, see it's empty with just the link to the page.

**Expected behavior:**
The feed should be displaying list of articles.

**Comment by evilpie** [comment] 2019-10-27 21:07
This is basically a duplicate of #202. The RSS items use a relative path in `<link>`.

**Comment by evilpie** [comment] 2019-10-27 21:27
>xml:base may be used to control how relative URIs are resolved.

https://validator.w3.org/feed/docs/atom.html

**Comment by nt1m** [comment] 2019-10-28 10:00
Duplicate of #202

**Closed by nt1m** 2019-10-28 10:00 UTC
