### ISSUE TITLE
Excessive memory consumption

### ISSUE THREAD

**Issue by notonymous** [nt1m/livemarks#61] opened 2018-11-02 16:35 UTC
Running Livemarks 1.7
on Firefox Dev Edition 64.0b5 buildID 20181029164536
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

With Livemarks disabled (and Firefox running as a background application), Fx consumes less than 350MB of memory on my Win7 machine.

If I enable Livemarks and leave Fx running in the background, then around the feed refresh interval (15 minutes in my case) I see excessive memory usage with Fx growing to over 1GB; it may have eventually gone higher but I disabled Livemarks at this point in the experiments. If I disable Livemarks without restarting Fx, Fx memory usage drops back to something like 400MB.

I don't know if this is a memory leak or if Livemarks is just gobbling up memory temporarily,

**Comment by nt1m** [comment] 2018-11-02 19:41
Hi, thanks for reporting this!
Can you please share the feeds you have using the "Export feeds" functionality in the settings ?

**Comment by notonymous** [comment] 2018-11-02 20:04
[livemarks-opml.zip](https://github.com/nt1m/livemarks/files/2543966/livemarks-opml.zip)

**Comment by evilpie** [comment] 2018-11-04 12:12
I  couldn't really reproduces this. It would be good to get an about:memory report when this happens again.

**Comment by notonymous** [comment] 2018-11-05 21:30
[memory-report.zip](https://github.com/nt1m/livemarks/files/2550704/memory-report.zip)

"memory-report-before" is with Livemarks disabled.
"memory-report-after" is with Livemarks enabled, feeds are being updated, Fx memory consumption is growing.

**Comment by evilpie** [comment] 2018-11-06 11:35
The memory report indeed looks bad, but it's hard to tell what is actually happening.
The WebExtension process uses 1Gb of memory, but you also have 19 extensions installed (including some Mozilla extensions). I am not sure you can conclusively blame our extension when so many others are installed.

`375.78 MB (37.53%) ── heap-unclassified` is definitely bad, because it makes it impossible to tell what is going on. `195.76 MB (19.55%) ── event-targets` is very surprising, I don't think we are using that many event  listeners.

**Comment by notonymous** [comment] 2018-11-06 14:11
The problem only occurs with Livemarks enabled; if Livemarks is disabled, then I never see this problem. Also, there is a clear correlation between the memory consumption and a periodic feed update.

Perhaps there is an interaction between Livemarks and one of my other extensions, but Livemarks is either the culprit or the trigger.

**Comment by notonymous** [comment] 2018-11-12 15:01
It looks like it might be some interaction with uBlock Origin. With only uBlock Origin disabled, I don't see the same problem when I enable Livemarks.

I don't have any custom uBlock rules.

**Comment by hyegeek** [comment] 2018-11-15 14:21
Memory usage is killing me here too, but I'm not using uBlock. In fact, I have the same set of plugins on two other systems and only one of them is seeing the issue.

**Comment by danielmotaleite** [comment] 2018-11-20 23:59
another report of high memory usage, my pc is almost 100% memory usage. Stopped livemarks and cpu usage dropped (probably firefox gc was alwasy running) and after a few minutes 50% is free.
I used about:performance to see what was using cpu and livemarks was in high usage.

I do not use ublock, but i use umatrix.
Using Firefox 64beta on linux

As the original poster, i'm using the dev branch, so maybe related to that too

**Comment by danielmotaleite** [comment] 2018-11-21 00:36
checked the  umatrix logs and not no see any traffic being blocked... but also no not see the feed updates.

my feeds:
[livemarks-opml.xml.gz](https://github.com/nt1m/livemarks/files/2602108/livemarks-opml.xml.gz)

**Comment by juarezr** [comment] 2018-12-11 13:48
First, thanks for the work in this addon.
Livemarks is very useful for improving the experience while browsing web and getting updated in my work, finances, and daily life.

I noticed a memory degradation in a long running firefox with 2 tabs open.
In this case firefox was left running since yesterday when I left work.
This morning I noticed WebExtensions was using 818 MB memory. 
Livemarks accounts for:

	818.75 MB (WebExtensions) 
	├───190.65 MB (Livemarks)
	│   └───134.07 MB (event-targets)


After doing a GC in about:memory, these values simply disappers:

	123.46 MB (WebExtensions) 
	├───8.73 MB (Livemarks)
	│   └───5.36 MB (event-targets)

I hope this report could be valuable analysing the causes.

Bellow about:memory statistics:

firefox 63.0.3 64bits linux ubuntu
Livemarks 1.10

	-- about:memory Before GC -----------------------------------
	Main Process
	...
	Other Measurements
	...

	14 (100.0%) -- extensions
	├───1 (07.14%) ── Extension(id={b9b25e4a-bdf4-4270-868c-3f619eaf437d}, name="No PDF Download", baseURL=moz-extension://1136f056-7877-4c6e-bfec-319237a861d9/)
	├───1 (07.14%) ── Extension(id={c5867acc-54c9-4074-9574-04d8818d53e8}, name="Livemarks", baseURL=moz-extension://9d24ee77-3c41-4ef9-9044-e9149eb42a52/)
	├───1 (07.14%) ── Extension(id={e839c3f9-298e-4cd0-99e0-464431cb7c34}, name="Foxy Gestures", baseURL=moz-extension://fb28e475-919e-4c3a-8e50-8cfb5b21c9af/)
	├───1 (07.14%) ── Extension(id=@vivaldi-fox, name="VivaldiFox", baseURL=moz-extension://c3fd6193-8247-476c-829d-561b6697c6bb/)
	├───1 (07.14%) ── Extension(id=arc-dark-theme@afnankhan, name="Arc Dark Theme", baseURL=moz-extension://08d36598-f2cb-4859-975f-4e73e92b5ac3/)
	├───1 (07.14%) ── Extension(id=fix-dark-theme-input-boxes@virgulilla.com, name="Fix Dark Theme Input Boxes", baseURL=moz-extension://f46fb6fa-04fb-46d7-9563-c21ec740e708/)
	├───1 (07.14%) ── Extension(id=formautofill@mozilla.org, name="Form Autofill", baseURL=moz-extension://8abfd949-7ccd-48b7-ab43-2d455d52e0b8/)
	├───1 (07.14%) ── Extension(id=fxmonitor@mozilla.org, name="Firefox Monitor", baseURL=moz-extension://c0e75a54-5ad0-42e3-8876-42967816a12b/)
	├───1 (07.14%) ── Extension(id=jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@jetpack, name="Google search link fix", baseURL=moz-extension://56183f30-43b5-45ba-92e6-cb0d40ffab42/)
	├───1 (07.14%) ── Extension(id=redirector@einaregilsson.com, name="Redirector", baseURL=moz-extension://6cbca6e0-3283-4c85-825e-96e69b499375/)
	├───1 (07.14%) ── Extension(id=screenshots@mozilla.org, name="Firefox Screenshots", baseURL=moz-extension://f2ca9df2-a4e4-4a60-9c16-ed49391c09ca/)
	├───1 (07.14%) ── Extension(id=simple-translate@sienori, name="Simple Translate", baseURL=moz-extension://b30495fb-b881-467b-b564-25566e5a22b8/)
	├───1 (07.14%) ── Extension(id=uBlock0@raymondhill.net, name="uBlock Origin", baseURL=moz-extension://2b5a109f-c269-4beb-967c-8ce33c04019f/)
	└───1 (07.14%) ── Extension(id=webcompat@mozilla.org, name="Web Compat", baseURL=moz-extension://2be8cbdb-b5be-4a14-b98b-39914ad62403/)

	WebExtensions (pid 2301)
	Explicit Allocations

	818.75 MB (100.0%) -- explicit
	├──387.51 MB (47.33%) ── heap-unclassified
	├──261.96 MB (32.00%) -- window-objects
	│  ├──190.65 MB (23.29%) -- top(moz-extension://9d24ee77-3c41-4ef9-9044-e9149eb42a52/_generated_background_page.html, id=4294967302)
	│  │  ├──141.71 MB (17.31%) -- active/window(moz-extension://9d24ee77-3c41-4ef9-9044-e9149eb42a52/_generated_background_page.html)
	│  │  │  ├──134.07 MB (16.37%) -- dom
	│  │  │  │  ├──133.98 MB (16.36%) ── event-targets
	│  │  │  │  └────0.08 MB (00.01%) ++ (4 tiny)
	│  │  │  └────7.65 MB (00.93%) ++ (4 tiny)
	│  │  └───48.93 MB (05.98%) -- js-zone(0x7ff214421000)
	│  │      ├──47.92 MB (05.85%) -- strings
	│  │      │  ├──37.64 MB (04.60%) ++ (339 tiny)
	│  │      │  └──10.28 MB (01.26%) ++ string(<non-notable strings>)
	│  │      └───1.01 MB (00.12%) ++ (12 tiny)
	│  ├───47.50 MB (05.80%) ++ top(moz-extension://c3fd6193-8247-476c-829d-561b6697c6bb/_generated_background_page.html, id=4294967299)
	│  ├───19.88 MB (02.43%) ++ top(moz-extension://2b5a109f-c269-4beb-967c-8ce33c04019f/background.html, id=4294967306)
	│  └────3.93 MB (00.48%) -- (8 tiny)
	│       ├──0.81 MB (00.10%) ++ top(moz-extension://fb28e475-919e-4c3a-8e50-8cfb5b21c9af/_generated_background_page.html, id=4294967307)
	│       ├──0.59 MB (00.07%) ++ top(moz-extension://1136f056-7877-4c6e-bfec-319237a861d9/_generated_background_page.html, id=4294967301)
	│       ├──0.58 MB (00.07%) ++ top(moz-extension://6cbca6e0-3283-4c85-825e-96e69b499375/_generated_background_page.html, id=4294967300)
	│       ├──0.45 MB (00.05%) ++ top(moz-extension://b30495fb-b881-467b-b564-25566e5a22b8/_generated_background_page.html, id=4294967305)
	│       ├──0.42 MB (00.05%) ++ top(moz-extension://f2ca9df2-a4e4-4a60-9c16-ed49391c09ca/_generated_background_page.html, id=4294967317)
	│       ├──0.40 MB (00.05%) ++ top(moz-extension://2be8cbdb-b5be-4a14-b98b-39914ad62403/_generated_background_page.html, id=4294967297)
	│       ├──0.35 MB (00.04%) ++ top(moz-extension://8abfd949-7ccd-48b7-ab43-2d455d52e0b8/_generated_background_page.html, id=4294967303)
	│       └──0.33 MB (00.04%) ++ top(moz-extension://c0e75a54-5ad0-42e3-8876-42967816a12b/_generated_background_page.html, id=4294967304)
	├───65.52 MB (08.00%) -- js-non-window
	│   ├──34.68 MB (04.24%) -- zones
	│   │  ├──30.03 MB (03.67%) -- zone(0x7ff216753000)
	│   │  │  ├──18.37 MB (02.24%) ++ strings
	│   │  │  └──11.66 MB (01.42%) ++ (18 tiny)
	│   │  └───4.65 MB (00.57%) ++ (3 tiny)
	│   ├──28.98 MB (03.54%) -- runtime
	│   │  ├──16.82 MB (02.05%) -- gc
	│   │  │  ├──16.00 MB (01.95%) ── nursery-committed
	│   │  │  └───0.82 MB (00.10%) ++ (3 tiny)
	│   │  └──12.16 MB (01.48%) ++ (14 tiny)
	│   └───1.86 MB (00.23%) ++ (3 tiny)
	├───51.44 MB (06.28%) -- dom
	│   ├──51.40 MB (06.28%) ── structured-clone-holder [7839]
	│   └───0.04 MB (00.00%) ++ (2 tiny)
	├───25.38 MB (03.10%) ++ images/content/raster/used
	├───19.21 MB (02.35%) -- heap-overhead
	│   ├──14.99 MB (01.83%) ── bookkeeping
	│   └───4.22 MB (00.52%) ++ (2 tiny)
	└────7.72 MB (00.94%) ++ (20 tiny)

	-- about:after Before GC -----------------------------------
	WebExtensions (pid 2301)
	Explicit Allocations

	123.46 MB (100.0%) -- explicit
	├───37.02 MB (29.98%) -- heap-overhead
	│   ├──25.57 MB (20.71%) ── bin-unused
	│   ├──10.85 MB (08.79%) ── bookkeeping
	│   └───0.59 MB (00.48%) ── page-cache
	├───29.14 MB (23.60%) ── heap-unclassified
	├───27.91 MB (22.61%) -- window-objects
	│   ├───9.22 MB (07.47%) ++ top(moz-extension://2b5a109f-c269-4beb-967c-8ce33c04019f/background.html, id=4294967306)
	│   ├───8.73 MB (07.07%) -- top(moz-extension://9d24ee77-3c41-4ef9-9044-e9149eb42a52/_generated_background_page.html, id=4294967302)
	│   │   ├──6.48 MB (05.25%) -- active/window(moz-extension://9d24ee77-3c41-4ef9-9044-e9149eb42a52/_generated_background_page.html)
	│   │   │  ├──5.44 MB (04.41%) -- dom
	│   │   │  │  ├──5.36 MB (04.34%) ── event-targets
	│   │   │  │  └──0.08 MB (00.07%) ++ (4 tiny)
	│   │   │  └──1.04 MB (00.84%) ++ (4 tiny)
	│   │   └──2.25 MB (01.82%) -- js-zone(0x7ff214421000)
	│   │      ├──1.77 MB (01.43%) ++ strings
	│   │      └──0.48 MB (00.39%) ++ (11 tiny)
	│   ├───6.83 MB (05.53%) ++ top(moz-extension://c3fd6193-8247-476c-829d-561b6697c6bb/_generated_background_page.html, id=4294967299)
	│   └───3.14 MB (02.54%) -- (8 tiny)
	│       ├──0.55 MB (00.45%) ++ top(moz-extension://fb28e475-919e-4c3a-8e50-8cfb5b21c9af/_generated_background_page.html, id=4294967307)
	│       ├──0.45 MB (00.36%) ++ top(moz-extension://6cbca6e0-3283-4c85-825e-96e69b499375/_generated_background_page.html, id=4294967300)
	│       ├──0.40 MB (00.32%) ++ top(moz-extension://b30495fb-b881-467b-b564-25566e5a22b8/_generated_background_page.html, id=4294967305)
	│       ├──0.37 MB (00.30%) ++ top(moz-extension://f2ca9df2-a4e4-4a60-9c16-ed49391c09ca/_generated_background_page.html, id=4294967317)
	│       ├──0.37 MB (00.30%) ++ top(moz-extension://1136f056-7877-4c6e-bfec-319237a861d9/_generated_background_page.html, id=4294967301)
	│       ├──0.36 MB (00.29%) ++ top(moz-extension://2be8cbdb-b5be-4a14-b98b-39914ad62403/_generated_background_page.html, id=4294967297)
	│       ├──0.33 MB (00.26%) ++ top(moz-extension://8abfd949-7ccd-48b7-ab43-2d455d52e0b8/_generated_background_page.html, id=4294967303)
	│       └──0.31 MB (00.25%) ++ top(moz-extension://c0e75a54-5ad0-42e3-8876-42967816a12b/_generated_background_page.html, id=4294967304)
	├───24.14 MB (19.55%) -- js-non-window
	│   ├──11.37 MB (09.21%) -- zones
	│   │  ├───6.75 MB (05.47%) -- zone(0x7ff216753000)
	│   │  │   ├──3.56 MB (02.88%) -- realm([System Principal], shared JSM global)
	│   │  │   │  ├──2.40 MB (01.95%) ++ classes
	│   │  │   │  └──1.16 MB (00.94%) ++ (6 tiny)
	│   │  │   └──3.19 MB (02.58%) ++ (18 tiny)
	│   │  ├───4.28 MB (03.47%) -- zone(0x7ff216728000)
	│   │  │   ├──4.13 MB (03.34%) -- strings/string(<non-notable strings>)
	│   │  │   │  ├──3.57 MB (02.89%) ── gc-heap/latin1
	│   │  │   │  └──0.56 MB (00.45%) ── malloc-heap/latin1
	│   │  │   └──0.16 MB (00.13%) ++ (3 tiny)
	│   │  └───0.34 MB (00.27%) ++ (2 tiny)
	│   ├──11.09 MB (08.99%) -- runtime
	│   │  ├───4.18 MB (03.39%) -- gc
	│   │  │   ├──4.00 MB (03.24%) ── nursery-committed
	│   │  │   └──0.18 MB (00.15%) ++ (3 tiny)
	│   │  ├───3.98 MB (03.23%) ── atoms-table
	│   │  └───2.93 MB (02.37%) ++ (13 tiny)
	│   ├───1.67 MB (01.35%) ++ gc-heap
	│   └───0.00 MB (00.00%) ++ (2 tiny)
	├────3.74 MB (03.03%) ++ (21 tiny)
	└────1.52 MB (01.23%) ++ atoms

	Other Measurements

	23.13 MB (100.0%) -- decommitted
	└──23.13 MB (100.0%) ── js-non-window/gc-heap/decommitted-arenas

**Comment by evilpie** [comment] 2018-12-14 09:32
Not really a good idea, because one slow feed (i.e timeout) can block the whole progress for a while.

**Comment by nt1m** [comment] 2018-12-14 09:35
@evilpie Fair enough, I'm fine with whatever fix as long as it solves the memory issue then :)

**Comment by nt1m** [comment] 2018-12-14 09:38
@evilpie Just a random idea, we could also use`await Promise.race()`, and have the updating race with a 2 second timeout ?

**Comment by nt1m** [comment] 2018-12-14 09:38
Not sure how continuously spawning timeouts performs though

**Comment by shdon** [comment] 2018-12-19 15:53
Disabling uBlock Origin reduced the memory and CPU usage to negligible levels on my system (with Firefox using 2GB according to task manager, with about 2 dozen tabs open). With uBlock Origin enabled, the update makes the memory footprint rise to 8GB or more and makes the whole system unresponsive.

**Comment by Bill06** [comment] 2018-12-19 16:04
It seems that the new version 1,12 has solved this problem. At least in my case that wasn't related with uBlock Origin.

**Comment by evilpie** [comment] 2018-12-19 16:59
Oh, I guess b04da06e5b867ca7536f3963eadb5dcc6398fd1f at least partly? fixed this problem as well. We limit the number of concurrent XHR request, and looking at posted about:memory report `─133.98 MB (16.36%) ── event-targets` probably came from all those live XHR requests. (At least 3 listeners per XHR request times number of feeds)

**Comment by evilpie** [comment] 2018-12-23 10:38
@notonymous do you still run into this issue?

**Comment by evilpie** [comment] 2019-01-02 10:45
I assume this is fixed.

**Closed by evilpie** 2019-01-02 10:45 UTC
Labels: performance ⚡️

**Comment by notonymous** [comment] 2019-01-03 03:32
@evilpie
Sorry for the late response. No, I haven't seen this issue using the latest release of LM.

Thanks ...
