### ISSUE TITLE
Not able to process RSS feeds from localhost

### ISSUE THREAD

**Issue by gerrit-hohl** [nt1m/livemarks#476] opened 2024-03-02 08:08 UTC
**Add-on version**
Add-on version: 3.7

**Describe the bug**
I have used livemarks to read an RSS feed from a locally running web server (`localhost`) in my machine via HTTP. Until now it work like a charm, but after the latest update to version 3.7 (which was released yesterday) it stopped working.

If I open the developer tools while using the add-on, I oddly can see that the access was blocked with `NS_ERROR_BAD_DOM_URI`.
Funnily enough if I open the details, I see that the response was `200 OK`.
In addition I also see the successful request and response in the log of the local web server providing the RSS feed.
I assume the the details show the real network traffic, while the list shows how it was internally processed. Maybe?

If I deactivate the add-on, Firefox offers a download, which contains the RSS feed if downloaded. Also in the network tab of the developer tools I can see that everything is already: `200 OK` not just in the details, but also the list.
If I use a REST client add-on in Firefox, I can clearly see the RSS feed (means the content).
No problem here.

**To Reproduce**
1. Open a local RSS feed from localhost using HTTP

**Expected behavior**
Hm, that it works like before. 😏😆

**Extra context**
Let me know if you need any extra information.🙏

**Comment by gerrit-hohl** [comment] 2024-03-02 08:20
As additional information: After validating the RSS feed (maybe some special character or anything sneaked it which blocks the internal parsing of livemarks in some way or throws an error which is not visible in the console of the developer tools) and checking various aspects of the local web server, I just reverted to version 3.6 of livemarks. Works like a charm.

Means a change in the new version broke it for local access (at least for HTTP, don't know about HTTPS).

**Comment by nt1m** [comment] 2024-03-02 08:41
@evilpie Does this have something to do with the CVE?

**Comment by evilpie** [comment] 2024-03-03 14:00
I can't reproduce:
![image](https://github.com/nt1m/livemarks/assets/296445/b18c53f3-feff-426b-9d97-4e4e9961ec6f)

What is the exact URL that is causing issues?

**Comment by gerrit-hohl** [comment] 2024-03-03 15:09
@evilpie , it is `http://localhost:1234/rss2`.

**Comment by evilpie** [comment] 2024-03-04 11:06
Is it possible that this actually a problem with the content of the feed? Can you provide the XML?

**Comment by gerrit-hohl** [comment] 2024-03-04 11:10
That was actually one of my thoughts, too. So I reverted to version 3.6 - didn't change anything about the feed itself (means content wasn't modified in between and also the web service wasn't restarted) - and it worked again. Therefore I pretty sure that it is not the feed itself or anything the web server sends (status code, headers, etc.).

But let me have a look, if I can't provide something, and come back to you.

**Comment by evilpie** [comment] 2024-03-04 19:49
I suspect this is a duplicate of #477 and v3.8 when released will fix this.

**Comment by evilpie** [comment] 2024-03-05 13:34
@gerrit-hohl please test the new version

**Comment by JohnBoncek** [comment] 2024-03-05 22:31
Failing for me with version 3.8.  Older machine with 3.3 still works.  Both are running in Firefox on Windows 10.

**Comment by JohnBoncek** [comment] 2024-03-05 22:58
I found that if I re-add a feed in 3.8 it seems to work (at least it has all entries but I don't know yet if it will update).  However, it doesn't show the folder checkmark, which 3.3 does.  Is there a way to get 3.3 for a new install?

**Comment by evilpie** [comment] 2024-03-07 10:01
I just check. In a fresh profile and a fresh Livemarks install, v3.8 shows the checkmark for all visited feed bookmarks inside a "livemarks" folder.

**Comment by gerrit-hohl** [comment] 2024-03-10 05:03
Sorry for the late reply. 🙇

I just tested v3.8 and processing RSS feeds from localhost works again. 👍
Thanks, guys. 🙏

**Closed** 2024-03-10 05:21 UTC
