### ISSUE TITLE
No synchronization Live Bookmarks when Firefox Sync is activated

### ISSUE THREAD

**Issue by JUDADWN** [nt1m/livemarks#134] opened 2018-12-28 08:04 UTC
**Add-on version**
Add-on version: 1.14

**Describe the bug**
No synchronization Live Bookmarks when Firefox Sync is activated. Bookmarks were synced but after sync there are only simple Boomarks in the Bookmark Toolbar and no Live Bookmarks. Creating new Live Bookmarks through the addon results in disappearing Live Bookmarks on the other machine (so vice versa). All sync options on Firefox Sync are activated (checked)

**To Reproduce**
1. Install Live Bookmarks on first machine and create 2 Live Bookmarks on Bookmark Toolbar
2. Close FF on first machine
3. Open FF on second machine (let FF Sync sync all Addons & Bookmarks)
4. Addon is installed & Bookmarks were creatated on second machine (but only simple Bookmarks Folder)

**Expected behavior**
Syncing all: Addon aswell as Live Bookmarks

**Comment by evilpie** [comment] 2018-12-28 12:10
Duplicate of #22

**Closed by evilpie** 2018-12-28 12:10 UTC
