### ISSUE TITLE
Latest update (25-Jan-2021) created hundreds of ordinary bookmarks 

### ISSUE THREAD

**Issue by pnt103** [nt1m/livemarks#332] opened 2021-01-27 13:41 UTC
**Add-on version**
Add-on version: 3.2

**Describe the bug**
Today at lunchtime (UK/GMT), I found I had several hundred bookmarks, including multiple duplicates, from the BBC newsfeeds interspersed with my ordinary bookmarks.  Everything was normal this morning, but I see Livemarks had an (automatic) update earlier today.

**To Reproduce**

**Expected behavior**
I should see links to/from BBC newsfeeds only under the Livemarks folders I created for the RSS feeds.

**Extra context**
In the time it took me to fill out this issue form, Livemarks added over 60 bookmarks to the tail end of my bookmarks menu.  As an example, one (which I've not opened) entitled "Apple watch call saves cyclist swept into River Wye", URL https://www.bbc.co.uk/news/uk-england-hereford-worcester-55823987, appears six times, interspersed with others.

I have disabled Livemarks and the repeated adding of spurious bookmarks has stopped.

Livemarks 3.2 updated 25-January-2021, running in Firefox 76.0.1 (64-bit) under Windows 10 Pro.

**Comment by nt1m** [comment] 2021-01-27 15:24
This is strange, there hasn't been any significant change since 3.0 (October), maybe something Firefox is doing wrong on their side (they have been doing bookmarking updates for Firefox 84-86 and rolling out studies)? Note that January 25th was also when Firefox 85 got released.

Though you mentioned you're using Firefox 76, so I'm not really sure what could change here. Maybe @evilpie knows?

Also are you using Firefox 85 on any of your profiles? or syncing with a device using Firefox 85?

**Comment by djmagnifique** [comment] 2021-01-27 16:07
I had this issue as well on Firefox 84.0.2.  Updating to Firefox 85 seems to have fixed it so far.

**Comment by evilpie** [comment] 2021-01-27 16:17
In 84/85 Firefox developers made some significant changes to how bookmarks work, so it could be something was broken. Like Tim said our own code hasn't changed in this area for a while.

**Comment by pnt103** [comment] 2021-01-27 16:48
Aha... thank you all for the switft and helpful replies.  Yes, I do have another copy of Firefox syncing with the one that I saw the problem on, and that other one is Firefox 84.0.2.   So I'm more than willing to believe this is (yet another) Firefox bug rather than the fault of the Livemarks plugin.  Oddly, that 84.0.2 still has Livemarks running and not screwing up.  Still, time to fix my FF, I think.

**Comment by djmagnifique** [comment] 2021-01-30 19:11
Ok, I know that this topic has been closed and that I though that the issue was resolved however it isn't so pleas can you look into this again if you get time.

I have just deleted almost 2000 bookmarks for links to BBC pages.  I have attached an image of the links and as you will be able to see it is only a handful of pages that are getting bookmarked. 

I fully understand that it's not something to do with your code but just thought I'd make yo aware that it is still happening.

![firefox_VrBYqOP1Lk](https://user-images.githubusercontent.com/78096901/106365685-f7aeb700-632e-11eb-9297-61a46d7b6f7e.png)

**Comment by pnt103** [comment] 2021-01-30 20:30
Same here.  I've updated both copies of Firefox, hoping that might fix it, but it made no difference.  I've had to disable Livemarks, since I can't easily downgrade Firefox.

**Comment by evilpie** [comment] 2021-01-30 20:34
We would need some steps on how to reproduce this. I just tried subscribing to BBC in a clean profile and all bookmarks are in the "BBC News" folder. Do you have uncommon settings?

**Comment by evilpie** [comment] 2021-01-30 20:39
And more importantly do you have other extensions that could interfere for example [Default Bookmark Folder](https://addons.mozilla.org/en-US/firefox/addon/default-bookmark-folder/)?.

**Comment by pnt103** [comment] 2021-01-30 20:55
I do use Default Bookmark Folder, 3.1.0, 27-Jan-2021.  The other extensions I have are Adblock Plus, 3.10.2 29-Jan-2021, JavaScript Toggle On and Off, 0.2.4 30-Nov-2020, and Print/print Preview, 1.3 12-Jun-2020.

Apart from the plugins, my install of Firefox 85.0 64-bit is identical on both machines, one running Windows 10 Pro 64-bit and the other running Windows 7 Pro 64-bit.  Firefox on the Win 7 machine was updated a week or so ago, on the Win 10 machine, yesterday evening.  Both have been running Firefox in its various versions for years.

So it seems, from what's been said, that the issue has been caused by a recent change in Firefox.  Nevertheless, that's the platform we have to work with.

**Comment by evilpie** [comment] 2021-01-30 20:57
I suspect removing "Default Bookmark Folder" should solve this: https://github.com/teddy-gustiaux/default-bookmark-folder/issues/399 (Since Firefox 85 the last used bookmark folder is remembered by Firefox itself)

**Comment by pnt103** [comment] 2021-01-30 21:03
Removing  "Default Bookmark Folder" isn't an acceptable option for me, unless there's another way to make the normal Bookmarks Menu the default for new bookmarks.

**Comment by evilpie** [comment] 2021-01-30 21:05
Sure you just have to select "Bookmarks Menu" as folder once and in the future it will default there.
I am going to close this issue, there is nothing we are going to change here.

**Closed by evilpie** 2021-01-30 21:05 UTC

**Comment by djmagnifique** [comment] 2021-01-30 21:26
I also use 'Default Bookmark Folder'.  I'll disable it and see what happens.

Cheers.

**Comment by pnt103** [comment] 2021-01-30 23:31
Actually that doesn't make the Bookmarks Menu the default.  It makes whatever was the last place used the one that shows up in the menu - which, in my testing, is quite often the Livemarks folder I created.  Close, but no cigar.

**Comment by hoasis2** [comment] 2021-02-03 10:18
Same issue here.
 
> Sure you just have to select "Bookmarks Menu" as folder once and in the future it will default there.

Does not work, even though I have "selected Bookmarks Menu as folder once",

**Comment by djmagnifique** [comment] 2021-02-03 11:26
> 
> 
> Same issue here.
> 
> > Sure you just have to select "Bookmarks Menu" as folder once and in the future it will default there.
> 
> Does not work, even though I have "selected Bookmarks Menu as folder once",

Works fine for me and i'm not getting any more random bookmarks added since disabling 'Default Bookmark Folder' extension.
