### ISSUE TITLE
No way to tell whether I already read an item?

### ISSUE THREAD

**Issue by Existencielle** [nt1m/livemarks#110] opened 2018-12-17 19:33 UTC
Hello,

I today installed this addon (as I imagine many others did), because Firefox removed the feature. I was able to import all my old feeds, however now I cannot tell apart whether I read one of the items already or not.

It used to be, with the native feature in the previous FF version, that unread items had an orange icon while read items had a black one. Now instead it displays the favicon of the page that is referred to (if any, default icon otherwise), and it does not change in any way after I clicked one of them.

I see other threads here about asking for a "mark all as read" feature, which to me sounds like there already is a feature marking feed items as read. Am I doing something wrong?

**Comment by nt1m** [comment] 2018-12-17 19:43
Duplicate of #17

**Closed by nt1m** 2018-12-17 19:43 UTC
