### ISSUE TITLE
Add Firefox Sync support to Livemarks

### ISSUE THREAD

**Issue by MurzNN** [nt1m/livemarks#22] opened 2018-08-08 18:11 UTC
At now I can create Livemark items in extension settings in one Firefox instance, so it create a standard Bookmarks folder, that will synced to other Firefox instances via Firefox Sync.

But Livemark extension settings are not synced to other Firefox profiles, so on second Firefox they will not auto-updated (when first Firefox is unloaded).

I can create same livemark in second Firefox profile, but this action will create new bookmark folder with same name, so I will have 2 equal folders instead of one.

The best solution will be sync Livemark settings via Firefox Sync too - is this hard to implement?

**Comment by nt1m** [comment] 2018-08-09 08:41
Unfortunately, I think the bookmarks that are created are not guaranteed to have the same ID, so this would be hard to implement.

**Comment by MurzNN** [comment] 2018-08-09 08:54
If Firefox API don't allow to add custom fields or tags to bookmark folders, maybe try to find the right folder for Livemark via custom folder name, that users will set?

So, if on one Firefox instance I create livemark with name "Tech news", and on second - create livemark with same name, detect duplicate and reuse already exists folder?

For make sure that this is Livemarks folder, you can check existing `Open "<livemark name>"` item into this folder with url, matching current feed url.

**Comment by MurzNN** [comment] 2018-08-09 08:57
And why did you think that ID can be different? How Firefox Syncs do sync process of bookmarks? I think that it must compare the bookmark id, or some other unique field of item, for prevent creating duplicates.

**Comment by marczellm** [comment] 2018-08-14 07:40
@MurzNN This article details why and how Sync is a more complicated process than it seems:
 https://blog.nightly.mozilla.org/2018/05/14/deep-dive-new-bookmark-sync-in-nightly/

**Comment by ali1234** [comment] 2018-09-21 02:43
We could abuse the tag/comment field to implement this. It's a pity that folders don't have these properties. That would make the whole code base a lot more robust.

**Comment by eikaramba** [comment] 2018-10-18 23:41
thinking about manually copying the local storage from firefox instance A to instance B by setting the right ids of the folders on B (rest 1:1 copied)

**Comment by mastacheata** [comment] 2018-11-05 10:23
Even IF the ids change accross synced Fx instances, couldn't this be fixed by just storing an array of Ids for each Live bookmark folder or an object with a machine to folder id mapping?

**Comment by nt1m** [comment] 2018-11-05 10:55
@eikaramba If the bookmarks IDs are the same, the fix would be using browser.storage.sync instead of browser.storage.local. Of course, we'd have to migrate existing users from local to sync.

**Comment by eikaramba** [comment] 2018-11-05 11:10
indeed. I was also confused as i would expected them to be different from the discussion here. maybe someone else should try it too to confirm. But if it really turns out to be the same then that would be great as just changing the storage location should do the trick

**Comment by mhammond** [comment] 2018-11-06 01:29
sync is already syncing bookmarks created by this extension - see also https://bugzilla.mozilla.org/show_bug.cgi?id=1499881. Sync is also going to have a bad time when different devices each have this extension installed as they will both be fighting to keep the shared folder up-to-date with results I can't really predict.

Sync will try and reconcile the IDs across devices. So if you add a folder with the same name and at the same location in 2 different profiles, they will initially have different IDs. After syncing, sync will change the ID of one so the same ID is used across both profiles. Once they have the same ID, they will tend to be kepy in sync correctly - eg, renaming a folder or changing the title or url of a bookmark on one device will cause it to be changed on the other device.

All that said though, I'm not sure what this ticket is asking for?

**Comment by mastacheata** [comment] 2018-11-06 05:10
The bookmarks are synced and so is the extension, but the extension settings are not synced.
Currently computer A sets up the livemarks folder LM and computer B will see the changes as long as computer A is on(line). Computer B has no idea that LM is a livemarks folder. To the second computer it's only a "normal" bookmarks folder. There's also no way to tell B that LM is a livemarks folder. As soon as computer A is off(line) the bookmarks folder LM will no longer be synced with the feed on B. Yes it will be updated as soon as A is back, but that's not my use case. I want the same folder on my home and work computer to be a livemarks folder and want to keep updating the feed when I'm home.

**Comment by eikaramba** [comment] 2018-11-06 18:05
i can confirm what @mastacheata  writes. that was the case for me. after i just copied the whole Livemarks Database from A to B by copying the json manually and injecting it into B, everything worked perfectly.

**Comment by nt1m** [comment] 2018-11-06 18:08
I'd be happy to take pull requests for changing `browser.storage.local` to `browser.storage.sync` and also do the migration from `local` to `sync` for existing users.

Otherwise, I'd try to find time for it in the next months.

**Comment by nt1m** [comment] 2018-11-17 18:51
Hello everyone,

Could anyone test this version and see if they have any problem with it ?
https://send.firefox.com/download/364c4f0d5b/#uXzob7xy4gJNfnemFOZ9Hg

I mostly want to make sure the migration path from local to sync works properly and that sync actually works properly, before distributing the version to the wide public.

In this version, the livemarks should sync properly, and the list of livemarks in the settings should sync as well.

/cc @ali1234 @MurzNN @eikaramba @mastacheata @marczellm

**Comment by eikaramba** [comment] 2018-11-17 23:20
I installed it and then got 2 livemarks addons in my FF. The one you provided however had empty settings and did not show my feeds. so i guess it did not work. however maybe i did something wrong as i would have expected to upgrade the existing livemarks addon and not install a 2nd one.

**Comment by ali1234** [comment] 2018-11-17 23:21
That's expected I think. Same happens when you install from git.

**Comment by ali1234** [comment] 2018-11-18 02:26
I installed this along side the normal version, added a livemark, and waited for Firefox to sync to another system. This is what happened:

1. The bookmarks created by both versions of the add-on were synced across to the other system.
2. Only the newer version of the add-on was synced on to the other system.
3. The settings for the newer version of the add-on were deleted on both systems.

**Comment by nt1m** [comment] 2018-11-18 12:56
Nevermind, that last version was broken too. Normally the latest commit should handle migration from local storage to sync storage correctly... Whether sync works I'm not actually sure. 

Since I know migration from one storage to the other works. I think I'm simply going to push this update to the wide public.

**Comment by evilpie** [comment] 2018-11-21 11:14
I am going to revert Firefox sync support for causing to many issues for our users. (See #77)

I think we definitely need to think about how to handle the cases where the actual Firefox bookmarks and our storage is not synced up correctly, before that we should not try to enable syncing again.

**Comment by evilpie** [comment] 2018-12-23 15:30
New version with sync: https://send.firefox.com/download/bb4b2d3426/#QRzMf-cCwIucWAdEbZLK_w This should replace the existing Livemarks version and migrate your data.

@ali1234 @eikaramba @mastacheata

**Comment by gamin-mb** [comment] 2018-12-23 16:30
Version 1.15a seems to work for me.

I had to do this:
1. Make sure my feeds were exported to a file
2. Delete all bookmarks containing livemarks (otherwise Livemarks/Sync could convert them to regular folders during the sync)
3. Install Livemarks 1.15a on two separate computers
4. Disconnect one computer from the network (or pause sync)
5. Load my feeds file on the connected computer
6. Sync the connected computer
7. Load my feeds file on the disconnected computer
8. Connect and sync the disconnected computer

On both computers, one of the feeds had two lists of bookmarks, with the second list a copy of the first one. I got rid of the duplicates on the first computer (the one that was always connected) with "Reload Live Bookmark", and on the second computer with a combination of "Reload Live Bookmark" and "Sync".

Now everything appears to work, up to the checkmarks next to the titles I've read.

Thanks,

Martin

**Comment by evilpie** [comment] 2018-12-23 16:38
Thanks for testing, but all those steps really shouldn't be necessary. If you already had a previous version of Livemarks running one computer, those should have been synced to the other one. I think in the worst case you would end up with duplicates on both computers if both had their Livemarks before.

**Comment by evilpie** [comment] 2018-12-23 16:38
**Do export your feeds before testing this!**

**Comment by gamin-mb** [comment] 2018-12-23 18:52
> Thanks for testing, but all those steps really shouldn't be necessary. [...]

Without deleting the livemarks on both sides, the syncing process was constantly converting livemarks to regular folders, even if the new version of Livemarks was installed (because there was always one side that had regular folders, even if the other side had a livemark with the same name). The only way I found to break this loop was to prevent syncing, remove the folders/livemarks, and start from scratch.

**Comment by evilpie** [comment] 2019-01-01 17:45
We released version 1.5 with sync support.

**Closed by evilpie** 2019-01-01 17:45 UTC
Labels: parity 🔥

**Comment by gamin-mb** [comment] 2019-01-03 12:37
> 
> 
> We released version 1.5 with sync support.

Hmmm. I searched for version 1.5 and couldn't find it. Isn't it version 1.**15**?

**Comment by nt1m** [comment] 2019-01-03 12:38
@gamin-mb Yes, version 1.15, sorry

**Comment by nt1m** [comment] 2019-01-03 12:38
@gamin-mb Well, you should really get the latest one (1.16) however, since 1.15 has a bug on localized Firefox.

**Comment by gamin-mb** [comment] 2019-01-03 12:57
@nt1m I have 1.16; it was installed automatically when I updated my extensions. Around that time (yesterday), my livemarks were converted (again) to regular folders on my laptop. I don't know why, especially because my laptop had been off for several days. So I made sure both my computers had 1.16 installed, repeated the 8-step procedure I outlined here on December 23, and now both my computers have livemarks.

However, the livemarks on one of them didn't seem to update with "Reload Live Bookmark", but they updated upon forcing a sync. I'll keep posting here my observations.

**Comment by gamin-mb** [comment] 2019-01-03 17:43
More observations:

Setup number 3: Delete livemarks on both computers, sync, create 2 livemarks from scratch on the desktop computer, by visiting feeds and clicking "+ Add Livemark", then sync again:
 - Livemarks work fine on the desktop
 - They appear as regular folders on the laptop (no "Reload Live Bookmark" sub-menu)
 - In addition, the laptop showed all bookmarks from one livemark also as individual bookmarks in the folder that contains the two livemark folders

Setup number 4: Same as setup number 3, but create livemarks on the laptop computer first:
 - Livemarks work fine on the laptop
 - They appear as regular folders on the desktop (no "Reload Live Bookmark" sub-menu)

So it appears that livemarks are synced, but their "livemark" nature is not propagated to the second computer. The only setup that didn't have this problem was when sync was disabled and livemarks were loaded individually on each computer before re-enabling sync.

**Comment by jarau-de** [comment] 2019-01-08 13:44
Please fix this soon. Otherwise it's useless because of I'm working with five different computers and have (of course) sync enabled. Now I can use the livemarks only on one computer.
