### ISSUE TITLE
Feed icon rather than a "folder" icon? 

### ISSUE THREAD

**Issue by seannyyx** [nt1m/livemarks#126] opened 2018-12-22 13:56 UTC
If it's possible to replace the default folder icon with the feeds icon (same icon from feed that shows up in the folder on each feed link)
 
Thank you.

**Comment by evilpie** [comment] 2018-12-22 13:59
Duplicate of #83

**Closed by evilpie** 2018-12-22 13:59 UTC

**Comment by GrosBourrin** [comment] 2018-12-24 07:34
> 
> 
> If it's possible to replace the default folder icon with the feeds icon (same icon from feed that shows up in the folder on each feed link)
> 
> Thank you.

![rss2](https://user-images.githubusercontent.com/40931468/50379607-3e109280-064e-11e9-89ec-ea0f77e3ede0.png) https://github.com/GrosBourrin/FIREFOX-BLUE-MOON/blob/master/rss%20svg4.svg
![rss1](https://user-images.githubusercontent.com/40931468/50379609-436ddd00-064e-11e9-8266-2a27480cdcb9.png) https://github.com/GrosBourrin/FIREFOX-BLUE-MOON/blob/master/rss3.svg

right click on link then save target link

you can edit svg files with gravit from gravit.io
