### ISSUE TITLE
Tracking Protection blocks feeds from loading (Reddit feeds not loading...)

### ISSUE THREAD

**Issue by nicolaasjan** [nt1m/livemarks#203] opened 2019-09-11 18:51 UTC
**Add-on version**
Add-on version: 2.2

**Describe the bug**
Try to add a feed from old.reddit.com gives error.

**To Reproduce**
1. Go to [https://old.reddit.com/r/uBlockOrigin/](https://old.reddit.com/r/uBlockOrigin/).
2. Click on rss feed icon in the address bar.
3. Scroll down to '....' n/a
4. See error (screenshot below)

**Expected behaviour**
See the content of the feed and be able to successfully subscribe to it.
It should open [https://old.reddit.com/r/uBlockOrigin/.rss](https://old.reddit.com/r/uBlockOrigin/.rss).

**Extra context**
Any already existing feeds from old.reddit.com are not updating.
And yes, I have already tried disabling Tracking Protection in Firefox.
That does not make any difference.
Screenshot of the error:
![screenshot-error](https://user-images.githubusercontent.com/14093220/64725085-21660480-d4d4-11e9-8f81-62f0dde63f4f.png)

**Comment by nicolaasjan** [comment] 2019-09-29 09:58
I have pinpointed the cause of this.
Trying in an even cleaner new profile with the default preferences unchanged the Reddit feeds were loading fine!
Under 'Enhanced Tracking Protection' ---> 'Custom' ---> 'Tracking content' must be set to 'Only in Private Windows'...

![screenshot1](https://user-images.githubusercontent.com/14093220/65830341-e07d3680-e2ae-11e9-887b-7e7257b3bce2.png)

I don't really like that (never use private windows), but OK.
I guess uBlock Origin and uMatrix take care of the rest.

**Comment by nt1m** [comment] 2020-01-07 01:06
Duplicate of #38

**Closed by nt1m** 2020-01-07 01:06 UTC
Labels: duplicate
