### ISSUE TITLE
Firefox synchronization breaks this extension

### ISSUE THREAD

**Issue by grzegorz-janoszka** [nt1m/livemarks#115] opened 2018-12-20 07:43 UTC
Hi, I have two firefoxes (home and office) that synchronize their settings and bookmarks. Whatever I add with this plugin it is broken after the synchronization - all live feeds become static. Pretty much useless plugin if I have to add my feeds every single morning.

**Comment by nt1m** [comment] 2018-12-20 08:47
Duplicate of #22

**Closed by nt1m** 2018-12-20 08:47 UTC
